default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: task_manager_api_development

test:
  <<: *default
  database: task_manager_api_test

production:
  <<: *default
  database: task_manager_api_production
  username: postgres
  password: postgres
